all:
	gcc -Wall -Werror -fsanitize=address -lm -std=c11 first.c -o first
deg:
	gcc -Wall -Werror -fsanitize=address -lm -std=c11 -g first.c -o first
val:
	gcc -Wall -Werror -lm -std=c11 -g first.c -o first
ignore:
	gcc -lm -std=c11 -g first.c -o first
clean:
	rm -f first
