all:
	gcc -Wall -Werror -fsanitize=address -std=c11 third.c -o third
deg:
	gcc -Wall -Werror -fsanitize=address -std=c11 -g third.c -o third
val:
	gcc -Wall -Werror -std=c11 -g third.c -o third
clean:
	rm -f third
